### ISSUE TITLE
Missing tls_policy

### ISSUE THREAD

**Issue by binaryparadox** [ElGaton/postfix-tls-policy-list#1]
I'm not sure if this was a project you started and never finished, or if the `tls_policy` was never committed by mistake.

If it's the former, I'd love to see a project like this happen! I've been fiddling through writing my own tls_policy but this strikes me as the kind of thing that would benefit lots of people. Can we collaborate on something?

If it's the latter, can you commit the `tls_policy` file please :-)

**Comment by ElGaton** [comment]
I thought retrieving the TLS certificates on my own could be a "weak point" of the project:
1. I'd like list updates to be prepared automatically, so that I'd just need to review and commit them, and
2. I'd like the data to be validated by more than one person.

For this reason, I looked into creating a distributed project with the [BOINC framework](https://boinc.berkeley.edu/), but, due to a chronic lack of free time on my part, I never got around to code it (also, I need to figure out some details, such as weeding out invalid certificates - think about locally-trusted root CAs created by security suites for e-mail scanning) - hence the current lack of the `tls_policy` file.

**Comment by binaryparadox** [comment]
> I thought retrieving the TLS certificates on my own could be a "weak point" of the project:

Perhaps! There's a real lack of `tls_policy` examples in the wild :( I was sad when I couldn't crib from this project.

> 1. I'd like list updates to be prepared automatically, so that I'd just need to review and commit them, and
> 2. I'd like the data to be validated by more than one person.

Have you looked at https://github.com/EFForg/starttls-everywhere ? I ended up using the policy generation there as a source of inspiration. It seems like it would help with #2 :-)

> For this reason, I looked into creating a distributed project with the BOINC framework, but, due to a chronic lack of free time on my part, I never got around to code it (also, I need to figure out some details, such as weeding out invalid certificates - think about locally-trusted root CAs created by security suites for e-mail scanning) - hence the current lack of the tls_policy file.

I know how that goes. Thanks for replying to the issue. I'll close, and hopefully one day there will be a BOINC based project for me to revisit!
